# coding: utf-8

"""
    Pages

    The control plane for Pages

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pages_client.models.get_page_request import GetPageRequest

class TestGetPageRequest(unittest.TestCase):
    """GetPageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPageRequest:
        """Test GetPageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPageRequest`
        """
        model = GetPageRequest()
        if include_optional:
            return GetPageRequest(
                user = '',
                namespace = '',
                name = ''
            )
        else:
            return GetPageRequest(
                user = '',
                namespace = '',
                name = '',
        )
        """

    def testGetPageRequest(self):
        """Test GetPageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
