# coding: utf-8

"""
    Pages

    The control plane for Pages

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pages_client.models.write_page_response import WritePageResponse

class TestWritePageResponse(unittest.TestCase):
    """WritePageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WritePageResponse:
        """Test WritePageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WritePageResponse`
        """
        model = WritePageResponse()
        if include_optional:
            return WritePageResponse(
                user = '',
                namespace = '',
                name = '',
                content = ''
            )
        else:
            return WritePageResponse(
                user = '',
                namespace = '',
                name = '',
                content = '',
        )
        """

    def testWritePageResponse(self):
        """Test WritePageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
