# coding: utf-8

"""
    Pages

    The control plane for Pages

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pages_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_pages_get_page_post(self) -> None:
        """Test case for pages_get_page_post

        Gets a page.
        """
        pass

    def test_pages_write_page_post(self) -> None:
        """Test case for pages_write_page_post

        Writes a page.
        """
        pass


if __name__ == '__main__':
    unittest.main()
