# coding: utf-8

# flake8: noqa

"""
    Pages

    The control plane for Pages

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from pages_client.api.default_api import DefaultApi

# import ApiClient
from pages_client.api_response import ApiResponse
from pages_client.api_client import ApiClient
from pages_client.configuration import Configuration
from pages_client.exceptions import OpenApiException
from pages_client.exceptions import ApiTypeError
from pages_client.exceptions import ApiValueError
from pages_client.exceptions import ApiKeyError
from pages_client.exceptions import ApiAttributeError
from pages_client.exceptions import ApiException

# import models into sdk package
from pages_client.models.error import Error
from pages_client.models.get_page_request import GetPageRequest
from pages_client.models.get_page_response import GetPageResponse
from pages_client.models.page import Page
from pages_client.models.write_page_request import WritePageRequest
from pages_client.models.write_page_response import WritePageResponse
